# Generated by Django 5.2.5 on 2025-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_in_dormitory', models.BooleanField(default=False)),
                ('parent_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('sub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
