# Generated by Django 5.2.5 on 2025-09-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_student_id_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
