# Generated by Django 5.2.5 on 2025-09-02 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
