# Generated by Django 5.2.5 on 2025-09-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_sub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
